version: '3.8'

services:
  mariadb-master:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=supertajneheslo
      - MARIADB_REPLICATION_MODE=master
    ports:
      - "3307:3306"  # Port 3307 na hostiteli bude směřovat do 3306 v kontejneru
    networks:
      - replication_network

  mariadb-slave:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=supertajneheslo
    ports:
      - "3308:3306"  # Port 3308 na hostiteli bude směřovat do 3306 v kontejneru
    networks:
      - replication_network

networks:
  replication_network:
    driver: bridge
